name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure README exists
        run: |
          if [ ! -f README.md ]; then
            echo "README.md missing"; exit 1; fi
      - name: List repo files
        run: ls -la
